/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.dulceria.ui;


import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.dulceria.entities.DetalleVenta;
import mx.itson.dulceria.entities.Producto;
import mx.itson.dulceria.models.Busqueda;
import mx.itson.dulceria.models.OrdenamientoProducto;

/**
 *
 * @author ADRIANA
 */
public class MainFrame extends javax.swing.JFrame {

        Producto p1 = new Producto("ChocoDelight", 2.49, 150, 200, "Chocolate, azúcar, nueces", "2023-12-31", "SweetCo", 51);
        Producto p2 = new Producto("Jelly Joy", 1.99, 120, 150, "Gelatina, azúcar, sabores naturales", "2023-11-30", "CandyWorld", 36);
        Producto p3 = new Producto("CaramelCrunch", 3.29, 180, 250, "Caramelo, cacahuetes, chocolate", "2024-01-15", "SweetDwlights", 10);
        Producto p4 = new Producto("MintMelt", 1.79, 100.0, 120.0, "Menta, azúcar, chocolate", "2023-12-20", "FreshTreats", 72);
        Producto p5 = new Producto("FruityBurst", 2.99, 130.0, 180.0, "Frutas secas, azúcar, gelatina", "2024-02-28", "FruitCraze", 46);
        Producto p6 = new Producto("VanillaDream", 2.19, 160.0, 220.0, "Vainilla, azúcar, galletas", " 2023-12-10", "DreamSweets", 2);
        Producto p7 = new Producto("PeanutParadise", 3.49, 200.0, 280.0, "Cacahuetes, caramelo, chocolate", "2024-03-15", "NuttyJoy", 5);
        Producto p8 = new Producto("BerryBlast", 2.89, 140.0, 190.0, "Bayas, azúcar, gelatina", "2023-11-25", "BerryDelight", 165);
        Producto p9 = new Producto("AlmondDelight", 3.99, 180.0, 260.0, "Almendras, caramelo, chocolate", "2024-02-10", "AlmondJoy", 94);
        Producto p10 = new Producto("LemonLicious", 2.59, 120.0, 170.0, "Limón, azúcar, galletas", "2023-12-05", "ZestyTreats", 46);
        List<Producto> productos = new ArrayList();
        List<DetalleVenta> carrito = new ArrayList();
        int fila=-1;
        
        
    
    /**
     * Creates new form Tienda
     */
    public MainFrame() {
        initComponents();
        productos.add(p1);
        productos.add(p2);
        productos.add(p3);
        productos.add(p4);
        productos.add(p5);
        productos.add(p6);
        productos.add(p7);
        productos.add(p8);
        productos.add(p9);
        productos.add(p10);
        updateTable(productos);
    }
    
    public void updateTable(List<Producto> lista){
        DefaultTableModel model = (DefaultTableModel) tblProducto.getModel();
        model.setNumRows(0);
        for(Producto p : lista){
            model.addRow(new Object[]{
                p.getNombre(), p.getPrecioUnitario(), p.getStock()
            });
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();
        btnCarrito = new javax.swing.JButton();
        txfBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jcbOrden = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jspCantidad = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jmnMenu = new javax.swing.JMenuBar();
        mCarrito = new javax.swing.JMenu();
        mHistorial = new javax.swing.JMenu();
        mAlmacen = new javax.swing.JMenu();
        mAdministrador = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", ""},
                {"", "", ""},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProducto);
        if (tblProducto.getColumnModel().getColumnCount() > 0) {
            tblProducto.getColumnModel().getColumn(0).setResizable(false);
            tblProducto.getColumnModel().getColumn(1).setResizable(false);
            tblProducto.getColumnModel().getColumn(2).setResizable(false);
        }

        btnCarrito.setText("Agregar al carrito");
        btnCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCarritoMouseClicked(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        jcbOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Precio ▲", "Precio ▼", "Alfabetico ▲", "Alfabetico ▼" }));

        jLabel1.setText("Orden");

        jLabel2.setText("Cantidad:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCarrito))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(txfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscar)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarrito)
                    .addComponent(jspCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 610));

        mCarrito.setText("Carrito");
        mCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCarritoMouseClicked(evt);
            }
        });
        jmnMenu.add(mCarrito);

        mHistorial.setText("Historial");
        jmnMenu.add(mHistorial);

        mAlmacen.setText("Almacen");
        jmnMenu.add(mAlmacen);

        mAdministrador.setText("Administrador");
        jmnMenu.add(mAdministrador);

        setJMenuBar(jmnMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        updateTable(Busqueda.buscarProducto(productos, txfBuscar.getText()));
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void tblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoMouseClicked
        fila = tblProducto.rowAtPoint(evt.getPoint());
        
    }//GEN-LAST:event_tblProductoMouseClicked

    private void mCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCarritoMouseClicked
        Carrito carritoJD = new Carrito(null, true);
        carritoJD.setCarrito(carrito);
        carritoJD.setVisible(true);
    }//GEN-LAST:event_mCarritoMouseClicked

    private void btnCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCarritoMouseClicked

        if(fila!=-1){
                String nombre = String.valueOf(tblProducto.getValueAt(fila, 0));
                int stock = Integer.parseInt(String.valueOf(tblProducto.getValueAt(fila, 2)));
                int cantidad = (int) jspCantidad.getValue();
                if(stock<cantidad){
                        JOptionPane.showMessageDialog(this, "Solo nos quedan "+stock+" "+nombre+" lo sentimos");
                }else{
                    for(Producto p: productos){
                        if(p.getNombre().equalsIgnoreCase(nombre) && p.getStock()>=cantidad && cantidad!=0){
                        carrito.add(new DetalleVenta(p, cantidad));
                        p.setStock(p.getStock()-cantidad);
                            updateTable(productos);
                        }else if(cantidad==0){
                            JOptionPane.showMessageDialog(this, "Selecciona la cantidad a comprar");
                        }

                    }
                }
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona un producto");
        }
        
    }//GEN-LAST:event_btnCarritoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarrito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOrden;
    private javax.swing.JMenuBar jmnMenu;
    private javax.swing.JSpinner jspCantidad;
    private javax.swing.JMenu mAdministrador;
    private javax.swing.JMenu mAlmacen;
    private javax.swing.JMenu mCarrito;
    private javax.swing.JMenu mHistorial;
    private javax.swing.JTable tblProducto;
    private javax.swing.JTextField txfBuscar;
    // End of variables declaration//GEN-END:variables
}
